# Generated by Django 3.2.3 on 2021-05-24 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(blank=True, max_length=75, null=True)),
                ('gender', models.CharField(blank=True, max_length=75, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Practitioner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=75, null=True)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('gender', models.CharField(max_length=75)),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('deceasedBoolean', models.BooleanField(blank=True, default=False, null=True)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=75, null=True)),
                ('degree', models.CharField(blank=True, max_length=75, null=True)),
                ('issuer', models.CharField(blank=True, max_length=75, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='telecom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(blank=True, max_length=75, null=True)),
                ('value', models.CharField(blank=True, max_length=75, null=True)),
                ('use', models.CharField(blank=True, max_length=75, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=75, null=True)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('gender', models.CharField(max_length=75)),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('deceasedBoolean', models.BooleanField(blank=True, default=False, null=True)),
                ('photo', models.ImageField(upload_to='')),
                ('communication', models.CharField(blank=True, max_length=75, null=True)),
                ('generalPractitioner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Ref_by_GP', to='labsys.practitioner')),
            ],
        ),
        migrations.CreateModel(
            name='note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(blank=True, max_length=500, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Note_by', to='labsys.practitioner')),
            ],
        ),
        migrations.CreateModel(
            name='name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use', models.CharField(blank=True, max_length=7, null=True)),
                ('text', models.CharField(max_length=75)),
                ('family', models.CharField(blank=True, max_length=75, null=True)),
                ('given', models.CharField(blank=True, max_length=75, null=True)),
                ('prefix', models.CharField(blank=True, max_length=75, null=True)),
                ('suffix', models.CharField(blank=True, max_length=75, null=True)),
                ('period', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='labsys.period')),
            ],
        ),
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use', models.CharField(blank=True, max_length=75, null=True)),
                ('text', models.CharField(blank=True, max_length=250, null=True)),
                ('line', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=75, null=True)),
                ('district', models.CharField(blank=True, max_length=75, null=True)),
                ('state', models.CharField(blank=True, max_length=250, null=True)),
                ('postalCode', models.CharField(blank=True, max_length=250, null=True)),
                ('country', models.CharField(blank=True, max_length=250, null=True)),
                ('period', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='labsys.period')),
            ],
        ),
    ]
