# Generated by Django 3.2.3 on 2021-06-04 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricelist', models.CharField(blank=True, max_length=75, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pricelist_account', to='labsys.account')),
            ],
        ),
        migrations.RemoveField(
            model_name='observation',
            name='encounter',
        ),
        migrations.AddField(
            model_name='encounter',
            name='observation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encounter_observation', to='labsys.observation'),
        ),
        migrations.AddField(
            model_name='observation',
            name='interpretation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Testlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(blank=True, max_length=75, null=True)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('method', models.CharField(blank=True, max_length=75, null=True)),
                ('referenceRange_high', models.CharField(blank=True, max_length=75, null=True)),
                ('referenceRange_low', models.CharField(blank=True, max_length=75, null=True)),
                ('pricelist_included', models.ManyToManyField(blank=True, null=True, related_name='test_pricelist', to='labsys.Pricelist')),
            ],
        ),
        migrations.CreateModel(
            name='Sampletype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampletype', models.CharField(blank=True, max_length=75, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sampletype_test', to='labsys.testlist')),
            ],
        ),
        migrations.AddField(
            model_name='encounter',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encounter_testlist', to='labsys.testlist'),
        ),
        migrations.AddField(
            model_name='observation',
            name='test',
            field=models.ManyToManyField(through='labsys.Encounter', to='labsys.Testlist'),
        ),
    ]
