# Generated by Django 3.2.3 on 2021-06-05 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0002_auto_20210604_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='concact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patient_contact', to='labsys.contact'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='test',
            field=models.ManyToManyField(related_name='observation_testlist', through='labsys.Encounter', to='labsys.Testlist'),
        ),
    ]
