# Generated by Django 3.2.3 on 2021-05-26 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0002_auto_20210524_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='period',
        ),
        migrations.DeleteModel(
            name='contact',
        ),
        migrations.RemoveField(
            model_name='note',
            name='author',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='generalPractitioner',
        ),
        migrations.DeleteModel(
            name='qualification',
        ),
        migrations.DeleteModel(
            name='telecom',
        ),
        migrations.AlterField(
            model_name='name',
            name='period',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to='labsys.period'),
        ),
        migrations.DeleteModel(
            name='address',
        ),
        migrations.DeleteModel(
            name='note',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='Practitioner',
        ),
    ]
