# Generated by Django 3.2.3 on 2021-06-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0003_auto_20210605_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampletype',
            name='test',
        ),
        migrations.AddField(
            model_name='sampletype',
            name='test',
            field=models.ManyToManyField(related_name='sampletype_test', to='labsys.Testlist'),
        ),
    ]
