# Generated by Django 3.2.3 on 2021-05-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0003_auto_20210526_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='telecom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(max_length=75)),
                ('value', models.CharField(max_length=75)),
                ('use', models.CharField(max_length=75)),
                ('rank', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
