# Generated by Django 3.2.3 on 2021-05-26 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0004_telecom'),
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use', models.CharField(max_length=75)),
                ('text', models.CharField(max_length=250)),
                ('line', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=75)),
                ('district', models.CharField(default='Ahmedabad', max_length=75)),
                ('state', models.CharField(default='Gujarat', max_length=250)),
                ('postalCode', models.CharField(max_length=250)),
                ('country', models.CharField(default='India', max_length=250)),
                ('period', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='labsys.period')),
            ],
        ),
    ]
