# Generated by Django 3.2.3 on 2021-06-05 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0004_auto_20210605_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampletype',
            name='test',
        ),
        migrations.AddField(
            model_name='testlist',
            name='sampletype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='test_sampletype', to='labsys.sampletype'),
        ),
    ]
