# Generated by Django 3.2.3 on 2021-06-06 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0005_auto_20210605_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encounter',
            options={'ordering': ['-timedate']},
        ),
        migrations.AlterModelOptions(
            name='observation',
            options={'ordering': ['-timedate']},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='encounter',
            name='observation',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='account',
        ),
        migrations.AddField(
            model_name='observation',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observation_encounter', to='labsys.encounter'),
        ),
        migrations.RemoveField(
            model_name='encounter',
            name='test',
        ),
        migrations.AddField(
            model_name='encounter',
            name='test',
            field=models.ManyToManyField(related_name='Encounter_testlist', through='labsys.Observation', to='labsys.Testlist'),
        ),
        migrations.RemoveField(
            model_name='observation',
            name='test',
        ),
        migrations.AddField(
            model_name='observation',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observation_testlist', to='labsys.testlist'),
        ),
        migrations.AlterField(
            model_name='testlist',
            name='pricelist_included',
            field=models.ManyToManyField(blank=True, null=True, related_name='testlist_pricelist', to='labsys.Pricelist'),
        ),
        migrations.AlterField(
            model_name='testlist',
            name='sampletype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='testlist_sampletype', to='labsys.sampletype'),
        ),
    ]
