# Generated by Django 3.2.3 on 2021-05-26 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0005_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(blank=True, max_length=75, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Contact_Per_Address', to='labsys.address')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='labsys.name')),
                ('period', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='labsys.period')),
                ('telecom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Contact_Per_Telecom', to='labsys.telecom')),
            ],
        ),
    ]
