# Generated by Django 3.2.3 on 2021-06-06 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0006_auto_20210606_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='period',
            name='practitioner',
        ),
        migrations.AddField(
            model_name='patient',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patient_period', to='labsys.period'),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='practitioner_period', to='labsys.period'),
        ),
        migrations.AlterField(
            model_name='testlist',
            name='pricelist_included',
            field=models.ManyToManyField(blank=True, related_name='testlist_pricelist', to='labsys.Pricelist'),
        ),
    ]
