# Generated by Django 3.2.3 on 2021-05-26 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0006_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practitioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=75, null=True)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('gender', models.CharField(max_length=20)),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('deceasedBoolean', models.BooleanField(blank=True, default=False, null=True)),
                ('photo', models.ImageField(upload_to='')),
                ('qualification', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Practitioner_Address', to='labsys.address')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='Practitioner_name', to='labsys.name')),
                ('telecom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Practitioner_telecom', to='labsys.telecom')),
            ],
        ),
    ]
