# Generated by Django 3.2.3 on 2021-06-06 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0007_auto_20210606_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ObservationDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(blank=True, max_length=75, null=True)),
                ('alias', models.CharField(blank=True, max_length=75, null=True)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('method', models.CharField(blank=True, max_length=75, null=True)),
                ('unit', models.CharField(blank=True, max_length=75, null=True)),
                ('loinc_code', models.CharField(blank=True, max_length=75, null=True)),
                ('category', models.CharField(blank=True, max_length=75, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=75, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QualifiedInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high', models.CharField(blank=True, max_length=75, null=True)),
                ('low', models.CharField(blank=True, max_length=75, null=True)),
                ('age_high', models.PositiveIntegerField(blank=True)),
                ('age_low', models.PositiveIntegerField(blank=True)),
                ('observationdefinition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qualifiedinterval_observationdefination', to='labsys.observationdefinition')),
            ],
        ),
        migrations.AddField(
            model_name='observationdefinition',
            name='outsourced_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observationdefination_organization', to='labsys.organization'),
        ),
        migrations.AddField(
            model_name='observationdefinition',
            name='pricelist_included',
            field=models.ManyToManyField(blank=True, related_name='observationdefination_pricelist', to='labsys.Pricelist'),
        ),
        migrations.AddField(
            model_name='observationdefinition',
            name='sampletype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observationdefination_sampletype', to='labsys.sampletype'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='test',
            field=models.ManyToManyField(related_name='Encounter_observationdefination', through='labsys.Observation', to='labsys.ObservationDefinition'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observation_observationdefination', to='labsys.observationdefinition'),
        ),
        migrations.DeleteModel(
            name='Testlist',
        ),
    ]
