# Generated by Django 3.2.3 on 2021-05-26 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0008_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=75, null=True)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('deceasedBoolean', models.BooleanField(blank=True, default=False, null=True)),
                ('photo', models.ImageField(upload_to='')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Patient_Address', to='labsys.address')),
                ('concact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Patient_Contact', to='labsys.contact')),
                ('generalPractitioner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Ref_by_GP', to='labsys.practitioner')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Patient_Name', to='labsys.name')),
            ],
        ),
    ]
