# Generated by Django 3.2.3 on 2021-06-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0008_auto_20210606_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='communication',
            field=models.CharField(blank=True, choices=[('G', 'Gujarati'), ('Hi', 'Hindi'), ('Pa', 'Punjabi'), ('Kn', 'Kannada'), ('Ml', 'Malayalam'), ('Ne', 'Nepali'), ('Or', 'Odia'), ('Mr', 'Marathi'), ('Bn', 'Bengali'), ('T', 'Tamil'), ('Ur', 'Urdu'), ('E', 'English')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown'), ('O', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('A', 'Annulled'), ('D', 'Divorced'), ('I', 'Interlocutory'), ('L', 'Legally Separated'), ('M', 'Married'), ('P', 'Polygamous'), ('S', 'Never Married'), ('T', 'Domestic partner'), ('u', 'Unmarried'), ('W', 'Widowed')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='communication',
            field=models.CharField(blank=True, choices=[('G', 'Gujarati'), ('Hi', 'Hindi'), ('Pa', 'Punjabi'), ('Kn', 'Kannada'), ('Ml', 'Malayalam'), ('Ne', 'Nepali'), ('Or', 'Odia'), ('Mr', 'Marathi'), ('Bn', 'Bengali'), ('T', 'Tamil'), ('Ur', 'Urdu'), ('E', 'English')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown'), ('O', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='relationship',
            field=models.CharField(blank=True, choices=[('H', 'Husband'), ('W', 'Wife'), ('F', 'Father'), ('M', 'Mother'), ('B', 'Brother'), ('S', 'Sister'), ('Fr', 'Friend'), ('FI', 'Father in law'), ('MI', 'Mother in law'), ('BI', 'Brother in law'), ('SI', 'Sister in law'), ('O', 'Other(specify with name)')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown'), ('O', 'Other')], max_length=20, null=True),
        ),
    ]
