# Generated by Django 3.2.3 on 2021-05-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0009_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practitioner',
            name='address',
        ),
        migrations.AddField(
            model_name='practitioner',
            name='address',
            field=models.ManyToManyField(related_name='Practitioner_Address', to='labsys.address'),
        ),
        migrations.RemoveField(
            model_name='practitioner',
            name='telecom',
        ),
        migrations.AddField(
            model_name='practitioner',
            name='telecom',
            field=models.ManyToManyField(related_name='Practitioner_telecom', to='labsys.telecom'),
        ),
    ]
