# Generated by Django 3.2.3 on 2021-06-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0009_auto_20210607_1545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observationdefinition',
            options={'ordering': ['test']},
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'Active'), ('I', 'Inactive'), ('E', 'entered-in-error'), ('H', 'on-hold'), ('U', 'unknown')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(blank=True, choices=[('P', 'Periodic'), ('C', 'Cash'), ('T', 'Temporary')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='observationdefinition',
            name='category',
            field=models.CharField(blank=True, choices=[('SH', 'social-history'), ('I', 'imaging'), ('L', 'laboratory'), ('P', 'procedure'), ('S', 'survey'), ('E', 'exam'), ('T', 'therapy'), ('A', 'activity')], default='laboratory', max_length=75, null=True),
        ),
    ]
