# Generated by Django 3.2.3 on 2021-05-27 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0010_auto_20210526_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='telecom',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='concact',
        ),
        migrations.RemoveField(
            model_name='practitioner',
            name='telecom',
        ),
        migrations.AddField(
            model_name='telecom',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Contact_Telecom', to='labsys.contact'),
        ),
        migrations.AddField(
            model_name='telecom',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Patient_Telecom', to='labsys.patient'),
        ),
        migrations.AddField(
            model_name='telecom',
            name='practitioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Practitioner_Telecom', to='labsys.practitioner'),
        ),
    ]
