# Generated by Django 3.2.3 on 2021-06-14 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0010_auto_20210610_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=75, null=True)),
                ('status', models.CharField(blank=True, default='registered', max_length=75, null=True)),
                ('cancelled_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('totalnet', models.CharField(blank=True, max_length=75, null=True)),
                ('totalGross', models.CharField(blank=True, max_length=75, null=True)),
                ('paymentTerms', models.CharField(blank=True, max_length=200, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_participant', to='labsys.account')),
                ('lineItem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_observationdefination', to='labsys.observationdefinition')),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_note', to='labsys.note')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_participant', to='labsys.practitioner')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_recipient', to='labsys.organization')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_subject', to='labsys.patient')),
            ],
        ),
    ]
