# Generated by Django 3.2.3 on 2021-05-27 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0011_auto_20210527_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='period',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='period',
        ),
        migrations.RemoveField(
            model_name='name',
            name='period',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='name',
        ),
        migrations.RemoveField(
            model_name='practitioner',
            name='address',
        ),
        migrations.RemoveField(
            model_name='practitioner',
            name='name',
        ),
        migrations.AddField(
            model_name='address',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Contact_Address', to='labsys.contact'),
        ),
        migrations.AddField(
            model_name='address',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Patient_Address', to='labsys.patient'),
        ),
        migrations.AddField(
            model_name='address',
            name='practitioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Practitioner_Address', to='labsys.practitioner'),
        ),
        migrations.AddField(
            model_name='name',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Contact_Name', to='labsys.contact'),
        ),
        migrations.AddField(
            model_name='name',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Patient_Name', to='labsys.patient'),
        ),
        migrations.AddField(
            model_name='name',
            name='practitioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Practitioner_Name', to='labsys.practitioner'),
        ),
        migrations.AddField(
            model_name='period',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Patient_Period', to='labsys.patient'),
        ),
        migrations.AddField(
            model_name='period',
            name='practitioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Practitioner_Period', to='labsys.practitioner'),
        ),
    ]
