# Generated by Django 3.2.3 on 2021-06-17 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0011_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=75, null=True)),
                ('status', models.CharField(blank=True, default='registered', max_length=75, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('paymentDate', models.DateField(auto_now_add=True)),
                ('paymentAmount', models.FloatField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paymentreconciliation_note', to='labsys.note')),
                ('payment_issuer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paymentreconciliation_issuer', to='labsys.organization')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paymentreconciliation_period', to='labsys.period')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paymentreconciliation_issuer', to='labsys.invoice')),
            ],
        ),
    ]
