# Generated by Django 3.2.3 on 2021-05-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0012_auto_20210527_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='generalPractitioner',
            new_name='Practitioner',
        ),
        migrations.AlterField(
            model_name='address',
            name='use',
            field=models.CharField(choices=[('H', 'home'), ('W', 'work'), ('T', 'temp'), ('O', 'old'), ('B', 'billing')], max_length=75),
        ),
        migrations.AlterField(
            model_name='name',
            name='use',
            field=models.CharField(blank=True, choices=[('U', 'usual'), ('O', 'official'), ('T', 'temp'), ('N', 'nickname'), ('A', 'anonymous'), ('D', 'old'), ('M', 'maiden')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='telecom',
            name='system',
            field=models.CharField(choices=[('P', 'phone'), ('F', 'fax'), ('E', 'email'), ('U', 'url'), ('B', 'pager'), ('S', 'sms'), ('O', 'other')], max_length=75),
        ),
        migrations.AlterField(
            model_name='telecom',
            name='value',
            field=models.CharField(choices=[('H', 'home'), ('W', 'work'), ('T', 'temp'), ('O', 'old'), ('M', 'mobile')], max_length=75),
        ),
    ]
