# Generated by Django 3.2.3 on 2021-07-21 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0012_paymentreconciliation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='lineItem',
        ),
        migrations.AddField(
            model_name='encounter',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_encounter', to='labsys.invoice'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='due',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='totalGross',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='totalnet',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentreconciliation',
            name='paymentAmount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
