# Generated by Django 3.2.3 on 2021-07-21 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0013_auto_20210721_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreconciliation',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_received_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
