# Generated by Django 3.2.3 on 2021-08-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0014_paymentreconciliation_received_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paymentreconciliation',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
