# Generated by Django 3.2.3 on 2022-01-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0015_auto_20210805_1950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encounter',
            options={'ordering': ['timedate']},
        ),
        migrations.AddField(
            model_name='observation',
            name='high',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='low',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observationdefinition',
            name='qualifiedInterval_range',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qualifiedinterval',
            name='category',
            field=models.CharField(choices=[('R', 'reference'), ('C', 'critical'), ('A', 'absolute')], default='reference', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualifiedinterval',
            name='condition',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='qualifiedinterval',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown'), ('O', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='qualifiedinterval',
            name='gestationalAge',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='status',
            field=models.CharField(blank=True, choices=[('R', 'registered'), ('P', 'preliminary'), ('F', 'final'), ('A', 'amended')], default='registered', max_length=75, null=True),
        ),
    ]
