# Generated by Django 3.2.3 on 2022-01-08 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0016_auto_20220105_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='observation',
            name='price',
        ),
        migrations.CreateModel(
            name='ChargeItemDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=75, null=True)),
                ('title', models.CharField(blank=True, default='registered', max_length=75, null=True)),
                ('alias', models.CharField(blank=True, max_length=75, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, default='registered', max_length=75, null=True)),
                ('experimental', models.BooleanField(blank=True, default=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('approvalDate', models.DateTimeField(blank=True, null=True)),
                ('lastReviewDate', models.DateTimeField(blank=True, null=True)),
                ('value', models.PositiveIntegerField(blank=True, null=True)),
                ('effectivePeriod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='labsys.period')),
                ('partOf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ChargeItem_partof', to='labsys.chargeitemdefinition')),
                ('replaces', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ChargeItem_relaces', to='labsys.chargeitemdefinition')),
            ],
        ),
        migrations.CreateModel(
            name='ChargeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=75, null=True)),
                ('status', models.CharField(blank=True, default='billed', max_length=75, null=True)),
                ('occurrenceDateTime', models.DateTimeField(auto_now_add=True)),
                ('priceOverride', models.PositiveIntegerField(blank=True, null=True)),
                ('overrideReason', models.CharField(blank=True, max_length=200, null=True)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ChargeItem_account', to='labsys.account')),
                ('context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='labsys.encounter')),
                ('definitionCanonical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='labsys.chargeitemdefinition')),
                ('enterer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('partOf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='labsys.chargeitem')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='labsys.device')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='labsys.diagnosticreport')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='labsys.patient')),
            ],
        ),
    ]
