# Generated by Django 3.2.3 on 2022-01-08 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0017_auto_20220108_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticreport',
            name='category',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='code',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnositcreport_encounter', to='labsys.encounter'),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='identifier',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='status',
            field=models.CharField(blank=True, default='registered', max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnositcreport_patient', to='labsys.patient'),
        ),
        migrations.AlterField(
            model_name='chargeitem',
            name='context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chargeitem_encounter', to='labsys.encounter'),
        ),
        migrations.AlterField(
            model_name='chargeitem',
            name='enterer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chargeitem_enterer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chargeitem',
            name='partOf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chargeitem_partof', to='labsys.chargeitem'),
        ),
        migrations.AlterField(
            model_name='chargeitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chargeitem_device', to='labsys.device'),
        ),
        migrations.AlterField(
            model_name='chargeitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chargeitem_diagnosticreport', to='labsys.diagnosticreport'),
        ),
        migrations.AlterField(
            model_name='chargeitem',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chargeitem_patient', to='labsys.patient'),
        ),
        migrations.AlterField(
            model_name='chargeitemdefinition',
            name='effectivePeriod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chargeitemdefination_period', to='labsys.period'),
        ),
        migrations.AlterField(
            model_name='chargeitemdefinition',
            name='experimental',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='chargeitemdefinition',
            name='title',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='paymentreconciliation',
            name='payment_issuer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paymentreconciliation_orgnanization', to='labsys.organization'),
        ),
        migrations.AlterField(
            model_name='paymentreconciliation',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paymentreconciliation_invoice', to='labsys.invoice'),
        ),
    ]
