# Generated by Django 3.2.3 on 2022-01-08 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0018_auto_20220108_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='Sampletype',
            new_name='Specimen',
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='conclusion',
            field=models.CharField(blank=True, default='registered', max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='effectiveDateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='performer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diagnositcreport_performer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='presentedForm',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diagnositcreport_observation', to='labsys.observation'),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='resultsInterpreter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diagnositcreport_resultinterpreter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='specimen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diagnositcreport_specimen', to='labsys.specimen'),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='media_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diagnositcreport_media', to='labsys.media'),
        ),
    ]
