# Generated by Django 3.2.3 on 2022-01-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0019_auto_20220108_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargeitem',
            name='service',
        ),
        migrations.AddField(
            model_name='chargeitemdefinition',
            name='heading',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='chargeitemdefinition',
            name='is_profile',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='chargeitemdefinition',
            name='observations_included',
            field=models.ManyToManyField(blank=True, null=True, related_name='Chargeitem_observations', to='labsys.Observation'),
        ),
    ]
