# Generated by Django 3.2.3 on 2022-01-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0020_auto_20220110_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargeitemdefinition',
            name='observations_included',
            field=models.ManyToManyField(blank=True, null=True, related_name='Chargeitem_observations', to='labsys.ObservationDefinition'),
        ),
    ]
