# Generated by Django 3.2.3 on 2022-01-10 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0021_alter_chargeitemdefinition_observations_included'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observationdefinition',
            name='outsourced_to',
        ),
        migrations.RemoveField(
            model_name='observationdefinition',
            name='price',
        ),
        migrations.RemoveField(
            model_name='observationdefinition',
            name='pricelist_included',
        ),
        migrations.RemoveField(
            model_name='observationdefinition',
            name='sampletype',
        ),
        migrations.AddField(
            model_name='address',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contact_address', to='labsys.organization'),
        ),
        migrations.AddField(
            model_name='chargeitemdefinition',
            name='outsourced_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chargeitemdef_organization', to='labsys.organization'),
        ),
        migrations.AddField(
            model_name='chargeitemdefinition',
            name='pricelist_included',
            field=models.ManyToManyField(blank=True, related_name='chargeitemdef_pricelist', to='labsys.Pricelist'),
        ),
        migrations.AddField(
            model_name='chargeitemdefinition',
            name='specimen',
            field=models.ManyToManyField(blank=True, null=True, related_name='chargeitemdef_specimen', to='labsys.Specimen'),
        ),
        migrations.AddField(
            model_name='organization',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='alias',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_contact', to='labsys.contact'),
        ),
        migrations.AddField(
            model_name='organization',
            name='identifier',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='name',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='telecom',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_telecom', to='labsys.organization'),
        ),
        migrations.AlterField(
            model_name='chargeitemdefinition',
            name='effectivePeriod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chargeitemdef_period', to='labsys.period'),
        ),
        migrations.AlterField(
            model_name='chargeitemdefinition',
            name='observations_included',
            field=models.ManyToManyField(blank=True, null=True, related_name='chargeitemdef_observations', to='labsys.ObservationDefinition'),
        ),
    ]
