# Generated by Django 3.2.3 on 2022-01-12 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0022_auto_20220110_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='verified_by',
            new_name='final_by',
        ),
        migrations.RenameField(
            model_name='observation',
            old_name='entered_by',
            new_name='prelimnary_by',
        ),
        migrations.AddField(
            model_name='chargeitemdefinition',
            name='Note',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='amended_timedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='final_timedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='note',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='prelimnary_timedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observationdefinition',
            name='note',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='observationdefinition',
            name='specimen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observationdef_specimen', to='labsys.specimen'),
        ),
        migrations.AlterField(
            model_name='chargeitem',
            name='note',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='chargeitemdefinition',
            name='observations_included',
            field=models.ManyToManyField(blank=True, related_name='chargeitemdef_observations', to='labsys.ObservationDefinition'),
        ),
        migrations.AlterField(
            model_name='chargeitemdefinition',
            name='specimen',
            field=models.ManyToManyField(blank=True, related_name='chargeitemdef_specimen', to='labsys.Specimen'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='value',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='DiagnosticReport',
        ),
    ]
