# Generated by Django 3.2.3 on 2022-01-12 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0023_auto_20220112_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='chargeitem',
            name='product',
        ),
        migrations.AddField(
            model_name='account',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_contact', to='labsys.contact'),
        ),
        migrations.AddField(
            model_name='account',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_periodic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chargeitemdefinition',
            name='orderBy',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chargeitemdefinition',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chargeitem_device', to='labsys.device'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='observation',
            name='amended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observation_amended_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='observation',
            name='delivered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observation_delivered_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='observation',
            name='delivered_timedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='informed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observation_informed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='observation',
            name='informed_timedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='unit',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='observationdefinition',
            name='alias_sms',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='observationdefinition',
            name='formula',
            field=models.CharField(blank=True, db_column='Formula', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='observationdefinition',
            name='is_calculated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='observationdefinition',
            name='options',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='observationdefinition',
            name='tat',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observationdefinition',
            name='vmsg',
            field=models.CharField(blank=True, db_column='VMsg', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='observationdefinition',
            name='vrule',
            field=models.CharField(blank=True, db_column='VRule', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='observationdefinition',
            name='vrulemust',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='final_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observation_final_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='observation',
            name='prelimnary_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observation_prelimnary_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='observationdefinition',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observationdef_department', to='labsys.department'),
        ),
    ]
