# Generated by Django 3.2.3 on 2022-01-12 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0024_auto_20220112_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observationdefinition',
            name='qualifiedInterval_range',
        ),
        migrations.AddField(
            model_name='qualifiedinterval',
            name='text_as_normal',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='labsys.account'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='labsys.practitioner'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='labsys.organization'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='labsys.patient'),
        ),
        migrations.AlterField(
            model_name='qualifiedinterval',
            name='age_high',
            field=models.PositiveIntegerField(blank=True, default=150),
        ),
        migrations.AlterField(
            model_name='qualifiedinterval',
            name='age_low',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='qualifiedinterval',
            name='category',
            field=models.CharField(choices=[('R', 'reference'), ('C', 'critical'), ('A', 'absolute')], default='reference', max_length=10),
        ),
        migrations.AlterField(
            model_name='qualifiedinterval',
            name='high',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='qualifiedinterval',
            name='low',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
