# Generated by Django 3.2.3 on 2022-01-12 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0025_auto_20220112_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account', to='labsys.contact'),
        ),
        migrations.AlterField(
            model_name='address',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='address', to='labsys.contact'),
        ),
        migrations.AlterField(
            model_name='address',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='address', to='labsys.organization'),
        ),
        migrations.AlterField(
            model_name='address',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='address', to='labsys.patient'),
        ),
        migrations.AlterField(
            model_name='address',
            name='practitioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='address', to='labsys.practitioner'),
        ),
        migrations.AlterField(
            model_name='chargeitem',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ChargeItem', to='labsys.account'),
        ),
        migrations.AlterField(
            model_name='chargeitem',
            name='context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chargeitem', to='labsys.encounter'),
        ),
        migrations.AlterField(
            model_name='chargeitem',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chargeitem', to='labsys.patient'),
        ),
        migrations.AlterField(
            model_name='chargeitemdefinition',
            name='effectivePeriod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chargeitemdef', to='labsys.period'),
        ),
        migrations.AlterField(
            model_name='chargeitemdefinition',
            name='observations_included',
            field=models.ManyToManyField(blank=True, related_name='chargeitemdef', to='labsys.ObservationDefinition'),
        ),
        migrations.AlterField(
            model_name='chargeitemdefinition',
            name='outsourced_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chargeitemdef', to='labsys.organization'),
        ),
        migrations.AlterField(
            model_name='chargeitemdefinition',
            name='partOf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ChargeItemdef_partof', to='labsys.chargeitemdefinition'),
        ),
        migrations.AlterField(
            model_name='chargeitemdefinition',
            name='pricelist_included',
            field=models.ManyToManyField(blank=True, related_name='chargeitemdef', to='labsys.Pricelist'),
        ),
        migrations.AlterField(
            model_name='chargeitemdefinition',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chargeitem', to='labsys.device'),
        ),
        migrations.AlterField(
            model_name='chargeitemdefinition',
            name='replaces',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ChargeItemdef_relaces', to='labsys.chargeitemdefinition'),
        ),
        migrations.AlterField(
            model_name='chargeitemdefinition',
            name='specimen',
            field=models.ManyToManyField(blank=True, related_name='chargeitemdef', to='labsys.Specimen'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encounter', to='labsys.account'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encounter', to='labsys.invoice'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encounter', to='labsys.patient'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='practitioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encounter', to='labsys.practitioner'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='test',
            field=models.ManyToManyField(related_name='Encounter', through='labsys.Observation', to='labsys.ObservationDefinition'),
        ),
        migrations.AlterField(
            model_name='name',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='name', to='labsys.contact'),
        ),
        migrations.AlterField(
            model_name='name',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='name', to='labsys.patient'),
        ),
        migrations.AlterField(
            model_name='name',
            name='practitioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='name', to='labsys.practitioner'),
        ),
        migrations.AlterField(
            model_name='note',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='note', to='labsys.practitioner'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observation', to='labsys.encounter'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observation', to='labsys.observationdefinition'),
        ),
        migrations.AlterField(
            model_name='observationdefinition',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observationdefination', to='labsys.department'),
        ),
        migrations.AlterField(
            model_name='observationdefinition',
            name='specimen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observationdefination', to='labsys.specimen'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization', to='labsys.contact'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='concact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patient', to='labsys.contact'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patient', to='labsys.period'),
        ),
        migrations.AlterField(
            model_name='paymentreconciliation',
            name='payment_issuer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paymentreconciliation', to='labsys.organization'),
        ),
        migrations.AlterField(
            model_name='paymentreconciliation',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paymentreconciliation', to='labsys.period'),
        ),
        migrations.AlterField(
            model_name='paymentreconciliation',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paymentreconciliation', to='labsys.invoice'),
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='practitioner', to='labsys.period'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pricelist', to='labsys.account'),
        ),
        migrations.AlterField(
            model_name='qualifiedinterval',
            name='observationdefinition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qualifiedinterval', to='labsys.observationdefinition'),
        ),
        migrations.AlterField(
            model_name='telecom',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='telecom', to='labsys.contact'),
        ),
        migrations.AlterField(
            model_name='telecom',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='telecom', to='labsys.organization'),
        ),
        migrations.AlterField(
            model_name='telecom',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='telecom', to='labsys.patient'),
        ),
        migrations.AlterField(
            model_name='telecom',
            name='practitioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='telecom', to='labsys.practitioner'),
        ),
    ]
