# Generated by Django 3.2.3 on 2022-01-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0026_auto_20220112_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='test',
            field=models.ManyToManyField(related_name='Encounter', through='labsys.ChargeItem', to='labsys.ChargeItemDefinition'),
        ),
    ]
