# Generated by Django 3.2.3 on 2022-01-17 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0027_alter_encounter_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargeitem',
            name='definitionCanonical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chargeitem', to='labsys.chargeitemdefinition'),
        ),
        migrations.AlterField(
            model_name='observationdefinition',
            name='formula',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='observationdefinition',
            name='vmsg',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='observationdefinition',
            name='vrule',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
