# Generated by Django 3.2.3 on 2022-03-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0028_auto_20220117_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargeitem',
            name='overrideReason',
            field=models.CharField(blank=True, default='Registration', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='name',
            name='use',
            field=models.CharField(blank=True, choices=[('U', 'usual'), ('O', 'official'), ('T', 'temp'), ('N', 'nickname'), ('A', 'anonymous'), ('D', 'old'), ('M', 'maiden')], default='U', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='telecom',
            name='system',
            field=models.CharField(choices=[('P', 'phone'), ('F', 'fax'), ('E', 'email'), ('U', 'url'), ('B', 'pager'), ('S', 'sms'), ('O', 'other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='telecom',
            name='use',
            field=models.CharField(choices=[('H', 'home'), ('W', 'work'), ('T', 'temp'), ('O', 'old'), ('M', 'mobile')], max_length=10),
        ),
    ]
