# Generated by Django 3.2.3 on 2022-03-09 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0029_auto_20220307_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargeitemdefinition',
            name='observations_included',
        ),
        migrations.AddField(
            model_name='chargeitemdefinition',
            name='observations',
            field=models.ManyToManyField(related_name='chargeitemdef', through='labsys.Observation', to='labsys.ObservationDefinition'),
        ),
        migrations.AddField(
            model_name='observation',
            name='observation_def',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observation', to='labsys.chargeitemdefinition'),
        ),
    ]
