# Generated by Django 3.2.3 on 2022-03-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0029_auto_20220307_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='test',
            new_name='testfield',
        ),
        migrations.AddField(
            model_name='encounter',
            name='observations',
            field=models.ManyToManyField(related_name='encounter', through='labsys.Observation', to='labsys.ObservationDefinition'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='test',
            field=models.ManyToManyField(related_name='encounter', through='labsys.ChargeItem', to='labsys.ChargeItemDefinition'),
        ),
    ]
