# Generated by Django 3.2.3 on 2022-03-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0030_auto_20220309_1211'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='observation',
            name='observation_def',
        ),
        migrations.AddField(
            model_name='encounter',
            name='observations',
            field=models.ManyToManyField(related_name='encounter', through='labsys.Observation', to='labsys.ObservationDefinition'),
        ),
        
        migrations.AlterField(
            model_name='encounter',
            name='test',
            field=models.ManyToManyField(related_name='encounter', through='labsys.ChargeItem', to='labsys.ChargeItemDefinition'),
        ),
    ]
