# Generated by Django 3.2.3 on 2022-03-09 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0030_auto_20220309_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chargeitemdefinition',
            old_name='observations_included',
            new_name='observations',
        ),
    ]
