# Generated by Django 3.2.3 on 2022-03-09 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0031_auto_20220309_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chargeitemdefinition',
            old_name='observations',
            new_name='observations_included',
        ),
    ]
