# Generated by Django 3.2.3 on 2022-03-09 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0031_rename_observations_included_chargeitemdefinition_observations'),
        ('labsys', '0032_rename_observations_chargeitemdefinition_observations_included'),
    ]

    operations = [
    ]
