# Generated by Django 3.2.3 on 2022-03-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0033_merge_20220309_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargeitemdefinition',
            name='observations',
            field=models.ManyToManyField(blank=True, related_name='chargeitemdef', to='labsys.ObservationDefinition'),
        ),
    ]
