# Generated by Django 3.2.3 on 2022-03-09 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0034_alter_chargeitemdefinition_observations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargeitemdefinition',
            name='observations',
        ),
    ]
