# Generated by Django 3.2.3 on 2022-03-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0035_remove_chargeitemdefinition_observations'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargeitemdefinition',
            name='observations',
            field=models.ManyToManyField(blank=True, related_name='chargeitemdef', to='labsys.ObservationDefinition'),
        ),
    ]
