# Generated by Django 3.2.3 on 2022-03-11 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0036_chargeitemdefinition_observations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encounter',
            name='observations',
        ),
        migrations.AddField(
            model_name='chargeitem',
            name='observations',
            field=models.ManyToManyField(related_name='chargeitem', through='labsys.Observation', to='labsys.ObservationDefinition'),
        ),
        migrations.AddField(
            model_name='observation',
            name='chargeitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observation', to='labsys.chargeitem'),
        ),
    ]
