# Generated by Django 3.2.3 on 2022-03-12 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0037_auto_20220311_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='encounter',
        ),
    ]
