# Generated by Django 3.2.3 on 2022-03-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0038_remove_observation_encounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualifiedinterval',
            name='high',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='qualifiedinterval',
            name='low',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
