# Generated by Django 3.2.3 on 2022-04-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0039_auto_20220312_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargeitemdefinition',
            name='partOf',
        ),
        migrations.AddField(
            model_name='chargeitemdefinition',
            name='includes',
            field=models.ManyToManyField(blank=True, related_name='_labsys_chargeitemdefinition_includes_+', to='labsys.ChargeItemDefinition'),
        ),
        migrations.RemoveField(
            model_name='chargeitemdefinition',
            name='replaces',
        ),
        migrations.AddField(
            model_name='chargeitemdefinition',
            name='replaces',
            field=models.ManyToManyField(blank=True, related_name='_labsys_chargeitemdefinition_replaces_+', to='labsys.ChargeItemDefinition'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='status',
            field=models.CharField(blank=True, choices=[('R', 'Registered'), ('P', 'Preliminary'), ('F', 'Final'), ('I', 'Informed'), ('D', 'Delivered'), ('A', 'Amended')], default='registered', max_length=75, null=True),
        ),
    ]
