# Generated by Django 3.2.3 on 2022-04-22 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0040_auto_20220419_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargeitem',
            name='priceoverrideby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chargeitem_priceoverrideby', to=settings.AUTH_USER_MODEL),
        ),
    ]
