# Generated by Django 3.2.3 on 2022-05-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0041_chargeitem_priceoverrideby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='due',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='totalGross',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='totalnet',
        ),
        migrations.AlterField(
            model_name='observation',
            name='status',
            field=models.CharField(blank=True, choices=[('R', 'Registered'), ('P', 'Preliminary'), ('F', 'Final'), ('I', 'Informed'), ('D', 'Delivered'), ('A', 'Amended')], default='R', max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='paymentreconciliation',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'Active'), ('C', 'Cancelled'), ('E', 'Entered-in-error'), ('D', 'Draft')], default='A', max_length=75, null=True),
        ),
    ]
