# Generated by Django 3.2.3 on 2022-07-05 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0042_auto_20220518_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=75, null=True)),
                ('note', models.CharField(blank=True, max_length=75, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='chargeitemdefinition',
            name='titleheading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chargeitemdef', to='labsys.headings'),
        ),
    ]
