# Generated by Django 3.2.3 on 2022-07-05 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0043_auto_20220705_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargeitemdefinition',
            name='heading',
        ),
    ]
