# Generated by Django 3.2.3 on 2022-07-05 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0044_remove_chargeitemdefinition_heading'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chargeitemdefinition',
            old_name='titleheading',
            new_name='heading',
        ),
    ]
