# Generated by Django 3.2.3 on 2022-08-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0045_rename_titleheading_chargeitemdefinition_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='observationdefinition',
            name='default_value',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
