# Generated by Django 3.2.3 on 2022-08-15 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0047_auto_20220815_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observationdefinition',
            name='category',
        ),
    ]
