# Generated by Django 3.2.3 on 2022-08-15 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0048_alter_observationdefinition_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='observationdefinition',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observationdefination', to='labsys.testcategory'),
        ),
    ]
