# Generated by Django 3.2.3 on 2022-08-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0049_observationdefinition_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationdefinition',
            name='alias_sms',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='observationdefinition',
            name='vmsg',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
