# Generated by Django 3.2.3 on 2022-08-17 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0050_auto_20220816_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargeitemdefinition',
            name='category',
            field=models.CharField(blank=True, choices=[('SH', 'social-history'), ('I', 'imaging'), ('L', 'laboratory'), ('P', 'procedure'), ('S', 'survey'), ('E', 'exam'), ('T', 'therapy'), ('A', 'activity')], default='laboratory', max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='chargeitemdefinition',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chargeitemdef', to='labsys.department'),
        ),
        migrations.AddField(
            model_name='chargeitemdefinition',
            name='print_in_receipt',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='chargeitemdefinition',
            name='tat',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
