# Generated by Django 3.2.3 on 2022-08-29 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0051_auto_20220817_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargeitemdefinition',
            name='date',
        ),
    ]
