# Generated by Django 3.2.3 on 2022-11-30 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0052_remove_chargeitemdefinition_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='postalCode',
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(default='Ahmedabad', max_length=75),
        ),
    ]
