# Generated by Django 3.2.3 on 2022-11-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0053_auto_20221130_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='postalcode',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, default='Ahmedabad', max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(blank=True, default='India', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(blank=True, default='Ahmedabad', max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='line',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, default='Gujarat', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='text',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
