# Generated by Django 3.2.3 on 2022-11-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labsys', '0054_auto_20221130_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='text',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
